server {
    listen 80;
    listen [::]:80;
    server_name n8n.octavo.press;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        include /etc/nginx/proxy-params.conf;
        proxy_pass http://127.0.0.1:5678;

        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;

        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
