server {
    listen 80;
    listen [::]:80;
    server_name two.octavo.press;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        include /etc/nginx/snippets/proxy-params.conf;
        proxy_pass http://127.0.0.1:3002;
        proxy_read_timeout 60s;
    }
}
